---
# tasks file for vps
- name: Perform system-wide bootstrap configuration
  hosts: fedora
  become: true
  vars_files:
    - ../vaults/secrets.yml
  tasks:
    - name: bootstrap run
      import_tasks: bootstrap.yml
    - name: RH internal
      import_tasks: rh.yml
  handlers:
    - name: Update CA Trust
      command: update-ca-trust
